#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PropertyGuide.Droid.Resource", IsApplication=true)]

namespace PropertyGuide.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::PropertyGuide.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::PropertyGuide.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroidN.Resource.String.ApplicationName = global::PropertyGuide.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroidN.Resource.String.Hello = global::PropertyGuide.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_addtask = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_save = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int DescLabel = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int NameLabel = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int linearLayoutContainer = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int listViewProperties = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int menu_add_property = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int menu_delete_property = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int menu_save_property = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int tvDescription = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int tvPropertyName = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int txtDesc = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int txtName = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PropertyDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PropertyListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_main = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_propertydetails = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_PropertyGuide = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
